# Generated by Django 5.2.5 on 2025-08-17 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('name', 'creator')},
        ),
        migrations.AddField(
            model_name='list',
            name='is_deletable',
            field=models.BooleanField(default=True, help_text='Whether users can delete this list (False for system lists)'),
        ),
        migrations.AddField(
            model_name='list',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Whether users can edit this list (False for auto-generated lists)'),
        ),
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('custom', 'Custom List'), ('favorites', 'Favorites List'), ('creations', 'Your Creations List')], default='custom', help_text='Type of list - determines editing permissions and behavior', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('creator', 'list_type'), ('name', 'creator')},
        ),
    ]
