# Generated by Django 5.2.5 on 2025-08-17 14:51

from django.db import migrations


def create_default_lists_for_existing_users(apps, schema_editor):
    """
    Create default lists (Favorites and Your Creations) for existing users.
    """
    User = apps.get_model('auth', 'User')
    List = apps.get_model('stir_craft', 'List')
    Cocktail = apps.get_model('stir_craft', 'Cocktail')
    
    for user in User.objects.all():
        # Create "Your Creations" list
        creations_list, created = List.objects.get_or_create(
            creator=user,
            list_type='creations',
            defaults={
                'name': "Your Creations",
                'description': "All cocktails you've created - automatically updated",
                'is_editable': False,
                'is_deletable': False
            }
        )
        
        # Add all user's cocktails to the creations list
        if created:
            user_cocktails = Cocktail.objects.filter(creator=user)
            creations_list.cocktails.set(user_cocktails)
        
        # Create "Favorites" list
        favorites_list, created = List.objects.get_or_create(
            creator=user,
            list_type='favorites',
            defaults={
                'name': "Favorites",
                'description': "Your favorite recipes",
                'is_editable': True,
                'is_deletable': False
            }
        )


def reverse_create_default_lists(apps, schema_editor):
    """
    Remove default lists created by this migration.
    """
    List = apps.get_model('stir_craft', 'List')
    List.objects.filter(list_type__in=['creations', 'favorites']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0002_alter_list_unique_together_list_is_deletable_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_lists_for_existing_users,
            reverse_create_default_lists
        ),
    ]
