# Generated by Django 5.2.5 on 2025-08-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0003_auto_20250817_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text="Original cocktail this recipe is based on (if it's a variation)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='stir_craft.cocktail'),
        ),
    ]
