# Generated by Django 5.2.5 on 2025-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0004_cocktail_forked_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, help_text='Cocktail image - auto-populated from TheCocktailDB API during seeding', null=True, upload_to='cocktails/'),
        ),
    ]
