# Generated by Django 5.2.5 on 2025-08-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0005_cocktail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, help_text='Cocktail image - auto-populated from TheCocktailDB or user-uploaded', null=True, upload_to='cocktails/'),
        ),
    ]
