# Generated by Django 5.2.5 on 2025-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0007_update_ingredient_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('spirit', 'Spirit'), ('liqueur', 'Liqueur'), ('wine', 'Wine'), ('beer', 'Beer'), ('mixer', 'Mixer'), ('soda', 'Soda'), ('syrup', 'Syrup'), ('bitters', 'Bitters'), ('juice', 'Juice'), ('dairy', 'Dairy'), ('garnish', 'Garnish'), ('other', 'Other')], help_text='Category of ingredient for filtering and organization', max_length=20),
        ),
    ]
