# Generated by Django 5.2.5 on 2025-08-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0008_refined_ingredient_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='color',
            field=models.CharField(blank=True, default='Clear', help_text="Cocktail color for filtering (e.g., 'Red', 'Yellow', 'Clear')", max_length=20),
        ),
    ]
