# Generated by Django 5.2.5 on 2025-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0009_add_default_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='color',
            field=models.CharField(blank=True, choices=[('Clear', 'Clear'), ('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Brown', 'Brown'), ('Black', 'Black'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Cream', 'Cream'), ('Amber', 'Amber')], default='Clear', help_text='Cocktail color for filtering and visual identification', max_length=20),
        ),
    ]
