# Generated by Django 5.2.5 on 2025-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0010_add_color_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='attribution_text',
            field=models.CharField(blank=True, help_text="Attribution text for recipe source (e.g., 'Original recipe by...', 'Adapted from...')", max_length=200),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='attribution_url',
            field=models.URLField(blank=True, help_text='URL to the original recipe or source'),
        ),
    ]
