# Generated by Django 5.2.5 on 2025-08-24 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0011_cocktail_attribution_text_cocktail_attribution_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('name', 'creator')},
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(condition=models.Q(('list_type__in', ['favorites', 'creations'])), fields=('creator', 'list_type'), name='unique_system_lists_per_user'),
        ),
    ]
