# Generated by Django 5.2.5 on 2025-08-26 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0012_alter_list_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text="Original list this was copied from (if it's a fork)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='stir_craft.list'),
        ),
    ]
