# Generated by Django 5.2.5 on 2025-08-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0013_list_forked_from'),
    ]

    operations = [
    ]
