# Generated by Django 5.2.5 on 2025-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stir_craft', '0014_auto_20250826_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, help_text='Cocktail image - auto-populated from TheCocktailDB API during seeding', null=True, upload_to='cocktails/'),
        ),
    ]
